"""WP400 31A execution contracts and in-process runners.

Production isolation and subprocess exec are owned by 31B (`platform/worker`).
"""

from app.execution.contracts import (
    BLOCK_TYPES,
    DEFAULT_TIMEOUT_SEC,
    EXECUTION_STATUSES,
    EXIT_CRASHED,
    EXIT_FAILED,
    EXIT_SUCCESS,
    EXIT_TIMEOUT,
    JOB_KINDS,
    JOB_STATUSES,
    NOTEBOOK_RUNNER_ID,
    PYTHON_RUNNER_ID,
    TEST_RUNNER_ID,
    WP137_REQUIRED_FIELDS,
    ContractError,
    Diagnostics,
    ExecutionJob,
    ExecutionLimits,
    JobState,
    Reproducibility,
    ResultBlock,
    StructuredResult,
    hash_payload,
    new_execution_id,
    new_job_id,
    sha256_hex,
)
from app.execution.notebook_adapter import normalize_cells, run_notebook
from app.execution.python_runner import IN_PROCESS_LIBRARY_ONLY, run_callable, run_job, run_source
from app.execution.result_schema import (
    ResultSchemaError,
    load_result_schema,
    validate_structured_result,
    wp137_schema_path,
)
from app.execution.test_runner import (
    AssertionOutcome,
    AssertionSpec,
    HarnessReport,
    hash_harness,
    run_harness,
)

__all__ = [
    "BLOCK_TYPES",
    "DEFAULT_TIMEOUT_SEC",
    "EXECUTION_STATUSES",
    "EXIT_CRASHED",
    "EXIT_FAILED",
    "EXIT_SUCCESS",
    "EXIT_TIMEOUT",
    "IN_PROCESS_LIBRARY_ONLY",
    "JOB_KINDS",
    "JOB_STATUSES",
    "NOTEBOOK_RUNNER_ID",
    "PYTHON_RUNNER_ID",
    "TEST_RUNNER_ID",
    "WP137_REQUIRED_FIELDS",
    "AssertionOutcome",
    "AssertionSpec",
    "ContractError",
    "Diagnostics",
    "ExecutionJob",
    "ExecutionLimits",
    "HarnessReport",
    "JobState",
    "Reproducibility",
    "ResultBlock",
    "ResultSchemaError",
    "StructuredResult",
    "hash_harness",
    "hash_payload",
    "load_result_schema",
    "new_execution_id",
    "new_job_id",
    "normalize_cells",
    "run_callable",
    "run_harness",
    "run_job",
    "run_notebook",
    "run_source",
    "sha256_hex",
    "validate_structured_result",
    "wp137_schema_path",
]
